apiVersion: v1
kind: Secret
metadata:
  name: db-urls
  namespace: quiz-platform
type: Opaque
stringData:
  USER_DB_URL: postgres://user_service:pass1@quiz-postgres-rw:5432/user_db
  QUIZ_DB_URL: postgres://quiz_service:pass2@quiz-postgres-rw:5432/quiz_db
  RESULT_DB_URL: postgres://result_service:pass3@quiz-postgres-rw:5432/result_db