apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quiz-platform-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.apiGateway.name }}
            port:
              number: {{ .Values.apiGateway.port }}
      - path: /user
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.userService.name }}
            port:
              number: {{ .Values.userService.port }}
      - path: /quiz
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.quizService.name }}
            port:
              number: {{ .Values.quizService.port }}
      - path: /result
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.resultService.name }}
            port:
              number: {{ .Values.resultService.port }}